### PR TITLE
Add CocoaPods project generation support

### PR DESCRIPTION
**Pull request by dnkoutso**
closes https://github.com/uber/uber-poet/issues/23

We are in the process of evaluating certain number of modules in our dependency graph and we currently use CocoaPods. Adding support to this project will help us simulate various scenarios.

I am also planning on adding Bazel support.

cc @uber-mahyar2 Let me know if there are things you would like me to reconfigure or move around!

Usage:

```
pipenv run ./genproj.py --output_directory "./mockapp" --project_generator_type cocoapods --gen_type bs_flat
```

The default generator remains BUCK so it wont break existing clients.

### CODE REVIEW

**Comment by dnkoutso** [comment]
Will be adding an example for cocoapods project generation.

**Comment by dnkoutso** [comment]
I cant seem to fix the python formatting issues. It seems my own version is formatting differently than the one expected by CI, however I do not see any config file for formatting...hoping someone could help me here.

I also updated multisuite to work with cocoapods as well.

**Comment by uber-mahyar2** [comment]
> I cant seem to fix the python formatting issues. It seems my own version is formatting differently than the one expected by CI, however I do not see any config file for formatting...hoping someone could help me here.

Did you try running the flake8 & yapf binaries that come with pipenv or the ones installed on your machine? That might be the source of the difference.  

Did you try `pipenv install --dev` and then run `pipenv run flake8` for example.

Either way, I'm going to check it out and test it on my machine.

Thanks for doing this!

**Comment by uber-mahyar2** [comment]
Ok I added some instructions on how to run the tools like travis does.  Does it work on your end?

https://github.com/uber/uber-poet/blob/master/docs/CONTRIBUTING.md

> I would suggest running the dev tool versions that come with the repo, to avoid issues with travis CI not passing. Look at the .travis.yml to see what commands it executes. The versions they execute although are not ones that would actually update your code to automatically fix them, so a general pre-commit workflow would be:
```bash
pipenv install --dev  #only need to run this once
INTEGRATION=1 pipenv run pytest --cov=uberpoet --cov-report xml:cov.xml --cov-report term-missing  #fix failing tests
pipenv run yapf -ri uberpoet/ test/ *py  # -r = recursive , -i = in-place
pipenv run isort # isort fixes in place by default
pipenv run flake8 # manually fix any issues the flake8 linter brings up
```
> Make sure to check the .travis.yml file to see what is actually run in case this file is out of date.

**Pull request merged**
